# Generated by Django 3.1.5 on 2021-01-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='DEFAULT VALUE', null=True, upload_to='images/'),
        ),
    ]
